import type { AppId, AppDefinition } from "@/types";

export const apps: AppDefinition[] = [
  {
    id: "projects",
    name: "Projects",
    icon: "FolderKanban",
    description: "Explore my work",
    defaultWidth: 900,
    defaultHeight: 600,
  },
  {
    id: "experience",
    name: "Experience",
    icon: "Briefcase",
    description: "Career timeline",
    defaultWidth: 800,
    defaultHeight: 650,
  },
  {
    id: "terminal",
    name: "Terminal",
    icon: "Terminal",
    description: "Interactive CLI",
    defaultWidth: 700,
    defaultHeight: 450,
  },
  {
    id: "arcade",
    name: "Arcade",
    icon: "Gamepad2",
    description: "Mini games",
    defaultWidth: 600,
    defaultHeight: 500,
  },
  {
    id: "blog",
    name: "Blog",
    icon: "BookOpen",
    description: "Articles & thoughts",
    defaultWidth: 800,
    defaultHeight: 600,
  },
  {
    id: "resume",
    name: "Resume",
    icon: "FileText",
    description: "Download CV",
    defaultWidth: 700,
    defaultHeight: 800,
  },
  {
    id: "devops",
    name: "DevOps Lab",
    icon: "Server",
    description: "Architecture visualizer",
    defaultWidth: 950,
    defaultHeight: 650,
  },
  {
    id: "ai-assistant",
    name: "AI Assistant",
    icon: "Bot",
    description: "Ask about me",
    defaultWidth: 450,
    defaultHeight: 600,
  },
  {
    id: "settings",
    name: "Settings",
    icon: "Settings",
    description: "Preferences",
    defaultWidth: 500,
    defaultHeight: 550,
  },
  {
    id: "about",
    name: "About",
    icon: "User",
    description: "Who am I",
    defaultWidth: 550,
    defaultHeight: 500,
  },
  {
    id: "contact",
    name: "Contact",
    icon: "Mail",
    description: "Get in touch",
    defaultWidth: 450,
    defaultHeight: 450,
  },
  {
    id: "gallery",
    name: "Gallery",
    icon: "Images",
    description: "Visual showcase",
    defaultWidth: 800,
    defaultHeight: 550,
  },
  {
    id: "github",
    name: "GitHub",
    icon: "Github",
    description: "Open source",
    defaultWidth: 750,
    defaultHeight: 600,
  },
  {
    id: "music",
    name: "Music",
    icon: "Music",
    description: "Ambient player",
    defaultWidth: 400,
    defaultHeight: 350,
  },
];

export function getApp(id: AppId): AppDefinition {
  return apps.find((a) => a.id === id)!;
}
